baseURL = 'https://example.local/'
languageCode = 'en-us'
title = 'Musik Stuff Notes'
theme = 'hugo-theme-relearn'


[params]
  collapsibleMenu = true
  themeVariant = ['zen-dark']
  highlightWrap = true
  subtitle = 'Some Musik Cheat Sheets'
  [params.contact]
    email = 'to@be.replaced.local'

[frontmatter]
  date = ['date', 'publishdate', 'pubdate', 'published', 'lastmod', 'modified']
  expiryDate = ['expirydate', 'unpublishdate']
  lastmod = [':git', 'lastmod', 'modified', 'date', 'publishdate', 'pubdate', 'published']
  publishDate = ['publishdate', 'pubdate', 'published', 'date']


[markup]
  defaultMarkdownHandler = 'goldmark'

enableEmoji = true
